inherit_from: .rubocop_todo.yml # TODO: remove this once worked through list

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/cert-quiz/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'test/test_helper.rb'
    - 'test/support/**/*'

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false
