source 'https://rubygems.org'

#Rails
gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Jruby Deps
platforms :jruby do
  gem "jruby-openssl", :platforms => :jruby
  gem 'activerecord-jdbc-adapter', '1.2.2' , :platforms => :jruby
  gem 'activerecord-jdbcmysql-adapter', '1.2.2' , :platforms => :jruby
  gem 'jdbc-mysql', :require => false , :platforms => :jruby
end

# Ruby Deps
platforms :ruby do
  gem 'sqlite3'
  gem 'therubyracer'
end

# Forms & Upload
gem "paperclip", "~> 3.0"
gem 'formtastic', " ~> 2.1.1"

# CSS 
gem 'less';
gem 'less-rails-bootstrap'
gem 'formtastic-bootstrap', :git => 'git://github.com/cgunther/formtastic-bootstrap.git', :branch => 'bootstrap2-rails3-2-formtastic-2-1'
gem 'bootstrap-will_paginate'

# JS
gem 'rails3-jquery-autocomplete'
gem 'tinymce-rails'
gem 'jquery-rails'

# Tool Libs

gem 'json'
gem 'tabulous'
gem 'enumerize'
gem 'will_paginate', '~> 3.0'

# Indexing /Searching
gem 'acts_as_indexed'

# Controller Gems 
gem 'devise' 

# Deploy with Capistrano
gem 'capistrano'

# Deal with Money 
gem 'money-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  platforms :jruby do
    gem 'jdbc-sqlite3'
    gem 'activerecord-jdbcsqlite3-adapter'
  end

  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino' , '~> 1.73.3'

  gem 'uglifier', '>= 1.0.3'
end

# for generating *.war file
group :development do
  gem 'warbler'

end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# To use debugger
# gem 'ruby-debug'
