source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "jruby-openssl", :platforms => :jruby
gem 'activerecord-jdbc-adapter', '1.2.2' 
gem 'activerecord-jdbcmysql-adapter', '1.2.2' 
gem 'jdbc-mysql', :require => false 

gem 'json'
gem 'formtastic', " ~> 2.1.1"
gem 'less'
gem 'less-rails-bootstrap'
gem 'formtastic-bootstrap', :git => 'git://github.com/cgunther/formtastic-bootstrap.git', :branch => 'bootstrap2-rails3-2-formtastic-2-1'
gem 'tabulous'
gem "paperclip", "~> 3.0"
gem 'enumerize'
gem 'acts_as_indexed'

gem 'tinymce-rails'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino' , '~> 1.73.3'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'devise'

gem 'bootstrap-will_paginate'
gem 'will_paginate', '~> 3.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'ruby-debug'
